# Generated by Django 6.0.6 on 2026-07-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=90, unique=True),
        ),
    ]
