# Generated by Django 6.0.6 on 2026-09-09 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('UNIVERSITY', 'University'), ('POLYTECHNIC', 'Polytechnic'), ('COLLEGE_OF_EDUCATION', 'College of Education')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership',
            field=models.CharField(blank=True, choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('PRIVATE', 'Private')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='regulatory_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SchoolSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulator', models.CharField(choices=[('NUC', 'National Universities Commission'), ('NBTE', 'National Board for Technical Education'), ('NCCE', 'National Commission for Colleges of Education')], max_length=10)),
                ('raw_category', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField()),
                ('fetched_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='schools.school')),
            ],
            options={
                'db_table': 'school_source_records',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['school', '-fetched_at'], name='school_sour_school__883264_idx'), models.Index(fields=['regulator', 'is_current'], name='school_sour_regulat_2b697f_idx')],
            },
        ),
    ]
