# Generated by Django 6.0.6 on 2026-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_ANSWER', 'New Answer'), ('NEW_COMMENT', 'New Comment'), ('NEW_QUESTION', 'New Question'), ('BEST_ANSWER', 'Best Answer'), ('VOTE', 'Vote'), ('MODERATOR_ASSIGNED', 'Moderator Assigned'), ('HUB_ACTIVATED', 'Hub Activated')], max_length=30),
        ),
    ]
