# Generated by Django 6.0.6 on 2026-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_ANSWER', 'New Answer'), ('NEW_COMMENT', 'New Comment'), ('NEW_QUESTION', 'New Question'), ('BEST_ANSWER', 'Best Answer'), ('VOTE', 'Vote'), ('MODERATOR_ASSIGNED', 'Moderator Assigned'), ('HUB_ACTIVATED', 'Hub Activated'), ('NEW_ACTIVATION_REQUEST', 'New Activation Request')], max_length=30),
        ),
    ]
