# Generated by Django 6.0.6 on 2026-08-02 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=90, unique=True)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('STAFF', 'Staff')], default='PUBLIC', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'static_pages',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_published', 'visibility'], name='static_page_is_publ_cfa607_idx')],
            },
        ),
    ]
