# Generated by Django 6.0.6 on 2026-07-03 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0001_initial'),
        ('schools', '0002_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('SOLVED', 'Solved')], default='OPEN', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='schools.department')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hubs.hub')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hub', '-created_at'], name='questions_hub_id_99caa5_idx'), models.Index(fields=['hub', 'status'], name='questions_hub_id_8ac6e7_idx'), models.Index(fields=['department'], name='questions_departm_096135_idx')],
            },
        ),
    ]
