# Generated by Django 6.0.6 on 2026-07-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
