# Generated by Django 6.0.6 on 2026-07-04 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_assignments', to='hubs.hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderator_assignments',
                'constraints': [models.UniqueConstraint(fields=('user', 'hub'), name='unique_moderator_per_hub')],
            },
        ),
        migrations.CreateModel(
            name='SchoolRepresentativeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_assignments', to='hubs.hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school_representative_assignments',
                'constraints': [models.UniqueConstraint(fields=('user', 'hub'), name='unique_representative_per_hub')],
            },
        ),
    ]
