# Generated by Django 6.0.6 on 2026-08-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_escalated', '-created_at'], name='reports_is_esca_95d033_idx'),
        ),
    ]
