site_name: Academia

theme:
  name: material

nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Project Plan: project-plan.md
  - Build Log Backend: BUILD_LOG_BACKEND.md
  - Build Log Frontend: BUILD_LOG_FRONTEND.md
  - Change Log: changelog.md
  - Features: feature-list.md
  - Database Schema: database-schema.md
  - API Contract: api-contract.md
  - Contributors: contributor-backlog.md
