# Generated by Django 6.0.6 on 2026-07-03 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='answers.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_votes',
                'indexes': [models.Index(fields=['answer'], name='answer_vote_answer__f8261f_idx')],
                'constraints': [models.UniqueConstraint(fields=('answer', 'user'), name='unique_answer_vote_per_user')],
            },
        ),
    ]
